language: ruby
rvm:
  - 2.4.3

addons:
  chrome: stable

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:{drop,create,migrate,seed}

branches:
  only:
  - master

secure: "BKAbGBgGWa4IL1SHoUOMrFTEjp0TaLqFd86W5mAxXnoA7ZoWfKGNaHrWgn9Et9KfTQg/V4RoIivoL58IxMBes1oqw62mY3pT1D7R18AjC+1uP89a81tBLSpEE133XHDSfNExeHaGHia9cg3unjgcpsNcA8UdyU2xMrq0TPqwIfUaZhAElTt6ZAJaORgna/PlA5nu3Afj4bqP8+FtFGQv0VcnctSPhHxCVbWczbPrDq1nraqMzP4urSRUjw0n0MrZ2huQlichHjx66gm8S3PB7wpQvmnLlfWojPypb9VaIQZ9fmlXW2htymaVaHRv3QDpRCiGEs4r472fLiaSQBaDiSZHhhYfH2HBi6+xmQq4Jusiy5mjNffBcxGRSKD193yDijqlrpCVaEG3EIT6GmqIqsddIePDS3rUfXRUkmXCMnlxm+zDJliY71hJ2curt0uoF+XEH8GZzNUuMZOsJG1SxChpAo7RnwaAMMpIAnCfRw1JAKhoMnkd7J8fvQWK72+wLbDKUuazgDiSTnqnf6IORQW8ZNmMOKxiM/VWUyCU1wfppTlycgvMnGnT9i8kYtyB7Hn8HSfynE6ZL7r0ERL/U6+71+9ovMpQ10Y2P8r00uyaCAahQHUQBlCRQ7uzid8jsmNGqsdZZVVCJx906SrlzVeCyq2QI3T/ZaNxaprt3yM="

secure: "aNoIgpDPFr+aKhm9p3UHmGXIBUuSFwQdLvOwMkXXHD7rKvV1ERjjTWepcuim03zjHBkkW1a6zugAvG9pClbQBHptieveOxTGG/e996i8JWh+RR2jh4ytZVsqllorH2GYDCIcBQujEA5p1uutn53m+vBqMz3Ot7QLSfiKpTv8+e36syhrr0GDEUpO7OOWytmUJSM5QPZKvuAM1X3q9QbrkYzZsJRAUk145x+s5XNdoMYD5KruhDhNkyz0x1ysD3Onv8PuK6AIWmwjKQ3hkgkiVUX6o3Htd13o7fWfv6MU4AKigd+ghs845CkNR053lA2DowYsIHXJRCJrIuwimH1WbunR/LcpRvpknMqOt0NbGy/Ijav1r9Bsq+x7UhJ1gOkHBNxMUDBjob9O0+7O/4uV3pBx7NhCEmERldprHbgw5amvvpp7lIFm7eDG9XhvqgJ/rpbxqWD9Ke2cZMZ4I6zdn3R5eGKnbmaz8MxRgHhTI8uH0gjqi4MPQsnlHR0nDwdaUCBIUhuMBM0PRX3ZFBPv61ywcSU+rWDzsndVOFZt/XF4n8zcSHmJQdoYLaNoTy89+JUvEj1d0J9HaMm/872SH4e6Q8yENE/kuVnkMMe3WLPOGvjuhORfIx0oBIQBjZkS7wSHGuyOn9cfy5z7KhAcRlPFPaEdX7Gptn9/hepo5AA="
