language: ruby
rvm:
  - 2.4.3

addons:
  chrome: stable

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:{drop,create,migrate,seed}

branches:
  only:
  - master

env:
  secure: "BKAbGBgGWa4IL1SHoUOMrFTEjp0TaLqFd86W5mAxXnoA7ZoWfKGNaHrWgn9Et9KfTQg/V4RoIivoL58IxMBes1oqw62mY3pT1D7R18AjC+1uP89a81tBLSpEE133XHDSfNExeHaGHia9cg3unjgcpsNcA8UdyU2xMrq0TPqwIfUaZhAElTt6ZAJaORgna/PlA5nu3Afj4bqP8+FtFGQv0VcnctSPhHxCVbWczbPrDq1nraqMzP4urSRUjw0n0MrZ2huQlichHjx66gm8S3PB7wpQvmnLlfWojPypb9VaIQZ9fmlXW2htymaVaHRv3QDpRCiGEs4r472fLiaSQBaDiSZHhhYfH2HBi6+xmQq4Jusiy5mjNffBcxGRSKD193yDijqlrpCVaEG3EIT6GmqIqsddIePDS3rUfXRUkmXCMnlxm+zDJliY71hJ2curt0uoF+XEH8GZzNUuMZOsJG1SxChpAo7RnwaAMMpIAnCfRw1JAKhoMnkd7J8fvQWK72+wLbDKUuazgDiSTnqnf6IORQW8ZNmMOKxiM/VWUyCU1wfppTlycgvMnGnT9i8kYtyB7Hn8HSfynE6ZL7r0ERL/U6+71+9ovMpQ10Y2P8r00uyaCAahQHUQBlCRQ7uzid8jsmNGqsdZZVVCJx906SrlzVeCyq2QI3T/ZaNxaprt3yM="

  secure: "UYdpn8Bm7LO0UFv3xSehbUZNOUGubmoaUBSf4t74pKS+dmcNOiA9R5aE44rRGTrxhcSeDOAjMs8s+qUjtsDMsR3OvVW+/JIzO/UpdB31J1ZSETePJAMZtKTnE8w27Q3bgq35dNiJC1928DLNjNAnNXxNQpQo3/XbuNplkJtbTQH0VMBQ5iT0zTADf5+r4xJ57hIW73ep0j5jhLPNuu3ThO8tVX9+wXZmdBi7XS4OpHlCUOwv022kftx5nWKdkRhoI4waBR5kyi8RjPn+EX1bWqdTeaa+kU0xrQ4MNpe0WY62hPS+3YLmjIygjWmdM/IS8lWksO+FHSnsbDC0Er3rbzh5tHVEI/y5V2ke6PZKRGptJBQuhZQjmmQnXa/qw9SyW2AUvzO6POlDdw0+lk9c1txU4qo66+EntZIxCi1RQo7RLpZwawkFGnvQyh8e4zplDiDZeaBij54u9EvLCi+Gju9F+04ZsUi8wuBRGJ5YvodNLApuZK5SFOEysxf5iG5/XQY+Mge6RrI1OkT7efE7MS9iooW9W2apykOCZz4NyzWYgfFhpAYd/5D2gORb7cTxSZuyylGrSXOmhajyTd4n+x/Y51dDQPW/P945h9wVLFBbVRpPj2DeK3PeAHRtqhc6XawcaWm9HeumOIgLHJyqzXbbdQtynG1nyIKjpbiBN/k="

  secure: "wP19l/sI6lU81N4mi0INq6vQbsNK1hByItK5TDzDBqvtPtEQuriULCpTM2yCHKb/DRuz0xekJZs4DcLnS46mdD0x28ddKYtzNELrIhp7uQQCvBFN5d8o4NxLdND9X4UB/nQVuQHba8F6PrHfoBXe+Efcyo9tTK/HQjoFqg+O6jXmQx8/duPHA+tOFdAfnvTHtJuwaNlAKyzG3yngiE+RbwvtcijSVuj88SmamgIgbZCWQ7gkY1VubCp3Tc1YYY9diwDSka4T65R989NZI0yCh4JKQM274sjYNBWVPctNQR3jKLMvuudDyuXSvvPJrGGO8BazF8AkmxyOF1okhqu0sovxEmfnY695MVUI5ZVSWZp/oWJGiS69k3FwAIDLEhSYdfyCw0mphmq0hxNsco9xCMsX8ZlBavQDeUMdz/l128u+hiGJ76O/Oh78ZQZ5pLdGsIvTD0+YuULtuiK92Kqez+F2nmv0w0Ey1U2ujdVJ27T1BFn5TnUsu+Q410yd8JkX4h9GcbAnxEDlwOC/0zD92LOjMq87u/c+84aXtdma3RPLps/i8EZtlwmkr6Tabmd9ls76Tzt6locENpvtfDDd2A78V7NNrZKlCfm/7zMSfeRxPQaX+rWIaTYCwL3Tt8P4eOp3X4eCj4HOJdfPcYpdLCEiOHuotfyDI8auI5EbHxY="

  secure: "pMmIGZHUrQJpDg6ZsIH0HuKK1H8l78XecXPf0ivzYuVRvJZmn42w/bIQ9PTBtcYTzBFI6sbWY2T7u/1sdkrSUCEMOTcQ9OgvQ8mc5HP6ikY6U7z7jIid7v1SVAr6lip6m+Ug/q0CgtgF9H9ufkHkaUW1Z1e7Ubn0/YqdGEf50Jqj4BlbMhdpdsgYZN3MLVGaETgNNn8NRcBCTU8qK4VShvzsLS7nWIJmU+8/X0iy7QS3RkCeTBORXX5Q/gMsDya3kfr9DPBglpndZ6Q3lrR2k1ZUhwWgVCfxMO+4pmjWdxWSk7Q9GZifyJOFetRKS1cQwyneWrQUP7FOhwHa5oqBxUDVpGQ9MKJYiwSDU4e4wpUQU0gD6e//TcS1Vld/v5hOhq6+eojJF+fY0vYV281L9FCu83jpdKlJUuOkRPAg4ap6veMB8GK0IBZW7mL8aTTQS9CMNO1YyCP0Izf7f+9kfDyczlQzU8DUrnncrbTgeCICESXF7JDfy7FglDVTSWnCqvvcLxaLlVtKKow8tH1myTSQgHfZPXXTVVn3DxZ6z/IGg3Cu7dVoIbstg3eviAJ47JbYysiI60B/zCtqZK2eOD8JwQ5IeF/1DdlWvqrTDWwyySYDS7P5dDRPF94zW5sNk1Xr3J3thPdcQxQfMRUVP4H/6AmDU0UxUC9ofe36mBU="
