language: ruby
rvm:
  - 2.4.3

addons:
  chrome: stable

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:{drop,create,migrate,seed}

branches:
  only:
  - master

env:
    secure: "BKAbGBgGWa4IL1SHoUOMrFTEjp0TaLqFd86W5mAxXnoA7ZoWfKGNaHrWgn9Et9KfTQg/V4RoIivoL58IxMBes1oqw62mY3pT1D7R18AjC+1uP89a81tBLSpEE133XHDSfNExeHaGHia9cg3unjgcpsNcA8UdyU2xMrq0TPqwIfUaZhAElTt6ZAJaORgna/PlA5nu3Afj4bqP8+FtFGQv0VcnctSPhHxCVbWczbPrDq1nraqMzP4urSRUjw0n0MrZ2huQlichHjx66gm8S3PB7wpQvmnLlfWojPypb9VaIQZ9fmlXW2htymaVaHRv3QDpRCiGEs4r472fLiaSQBaDiSZHhhYfH2HBi6+xmQq4Jusiy5mjNffBcxGRSKD193yDijqlrpCVaEG3EIT6GmqIqsddIePDS3rUfXRUkmXCMnlxm+zDJliY71hJ2curt0uoF+XEH8GZzNUuMZOsJG1SxChpAo7RnwaAMMpIAnCfRw1JAKhoMnkd7J8fvQWK72+wLbDKUuazgDiSTnqnf6IORQW8ZNmMOKxiM/VWUyCU1wfppTlycgvMnGnT9i8kYtyB7Hn8HSfynE6ZL7r0ERL/U6+71+9ovMpQ10Y2P8r00uyaCAahQHUQBlCRQ7uzid8jsmNGqsdZZVVCJx906SrlzVeCyq2QI3T/ZaNxaprt3yM="

    secure: "XeaaA43Iq6H0FEDpPhTfhiHF+IiOqkztozJnJk8Qg/6XMrXJAROm+5x73OVT1FExUzclvLIu0zuNlwMnTZw8LcSym66bc4YlwffapK1+oTrhrp6Uxh3g2l+vc+S5aZ+iBEHBAwABkgmUcHe3ywsZhRz6LSHln8D+jIZVguRlQ5f9jucFujBNvuwM5OZCd/ODDcYIdMn+JsYBiJKtCEosHV2YqSwiLK5PZFBQWkX7YouqX4yx4TLA3UaDfPZjmtn2Z6fz5p0KxQ5ho4L478fCtv6RucmaSxFhpGvaKaAgvf+KPaZf+CQgmGTtLwTQrQJ4fshmXwrIHQST4NXty/uNo/5nAEbNcO5Iju4s8Ov3FJoyzDhd/k3GrfYkd0KOb0etlnchOFkQDfncyBlEPFjhL3qjSFfgxNo2dBFX63yy7iUWUjspqttMCphGr2YEE67uUjAOnBJQSDGshqGz/2cSGxwdMB2jlIZY6ZpbT1I6xRR8JU9wa4/HPE/2Gb0p/e05Jzzy7M2+jN24cq5MnoxPqOwUMjEy1RQ732KxkOWas5CAYtUeR2RGL/NdQg53CCZM++IZPMnne8FsK0yvvMmaFnK9xW4h7gYPxS4SnT9itrRWHrnINZtH+WJVDUWQt63p8ulExNmiPihd4TVfR7e4JyCvxllC/WzYiSKwWIoP9WM="

    secure: "cuadfNTU92t9RzXcYoOBOzQr3KwqxAC5CfAPbgzkmZIgttGa2mJv6sam0IDxUMl/X9VpaP/s18ET00/heTSShNnV1UKOA0Z3lMrAg9SrSjmVrcGGERLPguDSAI00O+ek9rmJ9WX+GgYyXD074DbNrlHMKz2dSJAwBjIftTOoomY9Ux0QbXGb1ILSe4v4XC3gCVQHlw99ZdpkdJGOBiaZVPd/K6D2YyDu9h7RQNZ7l+opcxnu271DGyPKg2zktpF6Carv43+hp3KT9XQmy3saRuECmPxJ3e+E6mXgvBpUnuFWrNhmrBZ1bxj+fgVdpI1AGXfKnqOHMFD+ZWdP+B3U4xImcE1nNArU6eysQJwl1EQ9KAMl0WnBRJ9HIq3pBzu1SsqW6SlzWi8E/MHDKBPrj1XRhJqa4JcZ8Jxqk4P4qjpjtxce3k3sQNvCoDl0EZ8jD3qsda5IQyapRyefgbedA9tdtXaittCfOhazQMlKfKeY8zPzaQVIj1kCy6HcNwnXtFSybbTn23Sf8K12edu3h3Gnsag29LFayBcLhMLn4i7Sxs56mSkCK93RmhdBb1jfniSeO6CUfRSpotEKQKIDcsR1kquQcI1kUrpWoe9uEUkdvqItrdsF8cqEUoydhmquFTrqlns+KP68/Qm9zZqlkvOTWvCpDkmjwpJICOdeX8Y="

    secure: "V4uwyBIh3lHLIBFsVi6HHZufBGjvSeLm9LiQkScojZq9ak0HbSg1kgJZxPfF5KOuatarCUp5S3kueva4tiIt+Kw9sMcoh4/WoAqhfpiac9w236wFKRafAqADv+CXYUhe39BGnWZpUUfj0R3kHaiYy/tl7sAsLklOBk56loBF1NthzmpJsocL39DTCuDy0LTxPA3BiKmCZypISu9cwh2q2SCYhRKNwaQpGR1RH7ADFhq3Ib4AjTzW69Tw779uVc1NBYQdFzNjtAzs03o02xcqHCWxiRTolCyfYd+1YXl6rXBHGOf/6fvLbRdKvYFdbyLyKdWu+R4ZBHDsHwEFwNIqjzbEChZPLP5YvE2IZzOe1YC+ikH/NRZGPuR8z0bqGgzZ4CRUcfC6vEvgDLpdRoI8rfqFMkPovMB7jGJZDWTUU6wZP0cSka1wJuzHFk69SpIlnPjS75RlEy+jzQj7p75AB9OuQZZ3EPkgob9k0EstcE7O0WALbKOwNxpxD4CyZ/V4vrU0xwm/93Nv/HZiyfbdiwvqybaaWPoLaielvy4WWEVdRD5g9UHzza9VYDyehiD64e+udMjuU+j9IqVqWwsopT5bnB1JPY0BLZkaSRXnr6udaAm9uqnGhxiRFuzAo0f0sdMbUaIKLEbKrB9gWH2jKDjGu5z+FFvCyYYsZ/Dnark="
